/* TAIXUAN_MONETIZATION_UI_V2_HEAVY_SINGLEPLAYER */
(()=>{
'use strict';
const KEY='taixuan-premium-wallet-v1',VERSION=2;
const RECHARGE=[{id:'jade-6',price:6,base:60,bonus:0},{id:'jade-30',price:30,base:300,bonus:30},{id:'jade-68',price:68,base:680,bonus:80},{id:'jade-128',price:128,base:1280,bonus:200},{id:'jade-328',price:328,base:3280,bonus:650},{id:'jade-648',price:648,base:6480,bonus:1600}];
const VIP_THRESHOLDS=[0,60,300,680,1280,2000,3280,5000,8000,10000,12800,16000,22000,30000,45000,65000];
const VIP_DAILY=[0,10,20,30,45,65,90,130,200,220,250,300,420,500,650,900];
const GROWTH=[['qi',1,'踏入炼气',100],['foundation',10,'筑基有成',180],['golden',15,'金丹初成',260],['nascent',19,'元婴出世',360],['spirit',23,'化神入世',500],['void',26,'炼虚破界',650],['unity',30,'合体归一',850],['mahayana',34,'大乘问道',1100],['tribulation',38,'渡劫在即',1500],['immortal',39,'飞升真仙',3000]].map(([id,realm,name,jade])=>({id,realm,name,jade}));
const VIP_REWARDS={
1:{jade:60,stones:30},2:{jade:100,stones:60,rare:2},3:{jade:150,stones:100,rare:4},4:{jade:200,stones:150,rare:6},5:{jade:300,stones:220,rare:8,relic:1},6:{jade:400,stones:300,rare:12,relic:2},7:{jade:600,stones:500,rare:20,relic:4},
8:{jade:1888,stones:1888,rare:88,relic:18,heal:true,fullProgress:true,title:'八荒至尊'},
9:{jade:500,stones:300,rare:10},10:{jade:600,stones:400,rare:12,relic:1},11:{jade:800,stones:600,rare:18,relic:3},12:{jade:1288,stones:1288,rare:48,relic:10,fullProgress:true,title:'太玄道君'},13:{jade:900,stones:800,rare:24,relic:4},14:{jade:1200,stones:1200,rare:32,relic:6},15:{jade:3888,stones:3888,rare:188,relic:38,tribulation:8,heal:true,fullProgress:true,title:'诸天仙尊'}
};
const PACKS=[
{id:'daily-1',name:'每日灵石小袋',tag:'每日',price:1,repeat:'daily',reward:{stones:18,rare:1},desc:'最便宜的顺手补给。'},
{id:'daily-6',name:'每日修行补给',tag:'每日',price:6,repeat:'daily',reward:{stones:88,rare:4,relic:1},desc:'灵石、材料一起补。'},
{id:'stone-rescue',name:'灵石告急礼包',tag:'缺什么补什么',price:6,repeat:'daily',reward:{stones:128},desc:'灵石见底时专门推给你。'},
{id:'injury-rescue',name:'重伤续命礼包',tag:'受伤推荐',price:6,repeat:'daily',reward:{stones:38,rare:3,heal:true},desc:'立即疗伤并补一批资源。'},
{id:'revenge-12',name:'战败翻盘礼包',tag:'刚输就卖',price:12,repeat:'loss',reward:{stones:168,rare:8,relic:1,heal:true},desc:'打输了就给你一个变强入口。'},
{id:'break-18',name:'破境冲刺礼包',tag:'修为将满',price:18,repeat:'realm',reward:{stones:188,rare:10,relic:2},desc:'瓶颈前集中补资源，不直接替你突破。'},
{id:'realm-30',name:'新境界庆典礼包',tag:'境界专属',price:30,repeat:'realm',reward:{stones:288,rare:18,relic:3,heal:true},desc:'每个境界都能买一次。'},
{id:'sect-30',name:'宗门进阶礼包',tag:'宗门',price:30,repeat:'daily',reward:{stones:188,contribution:120,rare:12},desc:'入宗之后专门补宗门贡献。'},
{id:'flash-68',name:'限时天命机缘箱',tag:'限时',price:68,repeat:'daily',reward:{stones:588,rare:38,relic:8},desc:'每日重氪箱，资源密度明显更高。'},
{id:'vip8-sprint',name:'VIP8 至尊冲刺礼包',tag:'VIP8节点',price:328,repeat:'once',reward:{jade:888,stones:888,rare:48,relic:8,heal:true},desc:'VIP7阶段专门把你往VIP8大节点推。'},
{id:'jade-188',name:'仙玉·资源兑换箱',tag:'仙玉消费',jadePrice:188,repeat:'unlimited',reward:{stones:108,rare:6},desc:'让充值得到的仙玉真正有地方花。'},
{id:'jade-888',name:'仙玉·豪华机缘箱',tag:'仙玉消费',jadePrice:888,repeat:'unlimited',reward:{stones:588,rare:38,relic:6},desc:'高价仙玉资源包。'}
];
let activeTab='recommend';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function fresh(){return{version:VERSION,jade:0,vipExp:0,totalCny:0,monthlyUntil:0,monthlyClaimDate:'',growthOwned:false,growthClaimed:[],vipClaimDate:'',vipMilestoneClaimed:[],firstBonusUsed:{},packBuys:{},receipts:[],titles:[],offerWindowEnd:Date.now()+30*60000}}
function load(){try{const raw=JSON.parse(localStorage.getItem(KEY)||'null')||{};return{...fresh(),...raw,version:VERSION,firstBonusUsed:{...(raw.firstBonusUsed||{})},growthClaimed:[...(raw.growthClaimed||[])],vipMilestoneClaimed:[...(raw.vipMilestoneClaimed||[])],packBuys:{...(raw.packBuys||{})},receipts:[...(raw.receipts||[])],titles:[...(raw.titles||[])]}}catch{return fresh()}}
function save(w){localStorage.setItem(KEY,JSON.stringify(w));updateCurrency(w);renderOfferChip()}
function gameState(){try{return window.__TAIXUAN_TEST__?.getState?.()||null}catch{return null}}
function today(){const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`}
function weekKey(){const d=new Date(),one=new Date(d.getFullYear(),0,1);return `${d.getFullYear()}-${Math.ceil((((d-one)/86400000)+one.getDay()+1)/7)}`}
function vipLevel(exp){let v=0;for(let i=0;i<VIP_THRESHOLDS.length;i++)if((Number(exp)||0)>=VIP_THRESHOLDS[i])v=i;return Math.min(v,15)}
function monthlyDays(w){return Math.max(0,Math.ceil((Number(w.monthlyUntil||0)-Date.now())/86400000))}
function addReceipt(w,label){w.receipts.unshift({at:Date.now(),label});w.receipts=w.receipts.slice(0,16)}
function progressRatio(){const t=document.getElementById('cultivationText')?.textContent||'';const m=t.match(/([\d.]+)\s*\/\s*([\d.]+)/);return m?Math.min(1,(Number(m[1])||0)/Math.max(1,Number(m[2])||1)):0}
function age(s){const t=s?.time||{},p=s?.player||{};const days=((Number(t.year)||1)-1)*360+((Number(t.month)||1)-1)*30+(Number(t.day)||1)-1;return (Number(p.startAge)||16)+Math.floor(days/360)}
function updateCurrency(w=load()){const el=document.querySelector('.ui-currency');if(!el)return;el.classList.add('ui-currency-live');el.innerHTML=`<b>仙玉</b><em>${Math.floor(w.jade||0)}</em><i>＋</i>`;el.setAttribute('role','button');el.setAttribute('tabindex','0');if(!el.dataset.shopV2){el.dataset.shopV2='1';el.onclick=()=>openShop('recommend');el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openShop('recommend')}}}}
function packKey(pack,s){const p=s?.player||{};if(pack.repeat==='daily')return `${pack.id}:${today()}`;if(pack.repeat==='weekly')return `${pack.id}:${weekKey()}`;if(pack.repeat==='realm')return `${pack.id}:r${p.realmIndex||0}`;if(pack.repeat==='loss')return `${pack.id}:l${p.battleLosses||0}`;return pack.id}
function canBuyPack(pack,w,s){if(pack.repeat==='unlimited')return true;return !w.packBuys[packKey(pack,s)]}
function rewardText(r){const a=[];if(r.jade)a.push(`仙玉${r.jade}`);if(r.stones)a.push(`灵石${r.stones}`);if(r.rare)a.push(`高阶灵材${r.rare}`);if(r.relic)a.push(`古修残片${r.relic}`);if(r.contribution)a.push(`宗门贡献${r.contribution}`);if(r.tribulation)a.push(`渡劫灵质${r.tribulation}`);if(r.heal)a.push('伤势清零');if(r.fullProgress)a.push('当前境界修为直接圆满');if(r.title)a.push(`称号【${r.title}】`);return a.join(' · ')}
function persistGame(){document.getElementById('saveBtn')?.click();setTimeout(()=>document.querySelector('[data-close-modal]')?.click(),20);setTimeout(()=>document.querySelector('.nav-btn.active')?.click(),50)}
function grantGame(r){const api=window.__TAIXUAN_TEST__,s=gameState();if(!api||!s?.player)return false;const p=s.player;try{if(r.stones)api.v35SetPlayerForTest?.({stones:(Number(p.spiritStones)||0)+r.stones});if(r.contribution&&p.sect&&p.sect!=='散修')api.v35SetPlayerForTest?.({contribution:(Number(p.sectContribution)||0)+r.contribution});if(r.rare)api.v33AddMaterial?.('mat-rare-material',r.rare);if(r.relic)api.v33AddMaterial?.('mat-relic-fragment',r.relic);if(r.tribulation)api.v33AddMaterial?.('mat-v39-tribulation-essence',r.tribulation);if(r.heal)api.v39SetPlayerForTest?.({injury:0});if(r.fullProgress)api.v39SetPlayerForTest?.({progressFull:true});persistGame();return true}catch(e){console.error(e);return false}}
function relevantPackIds(){const s=gameState(),w=load(),p=s?.player||{},ids=[];if(!s)return ['daily-6','flash-68'];if((Number(p.spiritStones)||0)<12)ids.push('stone-rescue');if((Number(p.injury)||0)>0||((Number(p.hp)||1)<35))ids.push('injury-rescue');if(progressRatio()>=.78)ids.push('break-18');if((Number(p.battleLosses)||0)>0)ids.push('revenge-12');if((Number(p.realmIndex)||0)>0)ids.push('realm-30');if(p.sect&&p.sect!=='散修')ids.push('sect-30');if(vipLevel(w.vipExp)===7)ids.unshift('vip8-sprint');ids.push('daily-6','flash-68','jade-188');return [...new Set(ids)].slice(0,7)}
function nextNode(level){if(level<8)return 8;if(level<12)return 12;if(level<15)return 15;return 15}
function nodeCopy(level,w){const node=nextNode(level),need=Math.max(0,(VIP_THRESHOLDS[node]||0)-(w.vipExp||0));return node===8?`VIP8是第一重大节点，距VIP8还差 ${need} 经验`:node===12?`下一次大奖在VIP12，还差 ${need} 经验`:node===15?`终极节点VIP15，还差 ${need} 经验`:'已到当前最高节点'}
function ensureOverlay(){let o=$('uiShopOverlay');if(o)return o;o=document.createElement('div');o.id='uiShopOverlay';o.className='ui-shop-overlay hidden';o.innerHTML=`<section class="ui-shop-sheet" role="dialog" aria-modal="true"><header class="ui-shop-head"><div><span>单机重氪测试服</span><h2>仙玉商行</h2></div><button id="uiShopClose">×</button></header><div id="uiShopWallet" class="ui-shop-wallet"></div><div class="ui-shop-sandbox">全部为本机模拟充值 · 不接真实支付 · 不会产生真实扣款。</div><nav class="ui-shop-tabs"><button data-shop-tab="recommend">推荐</button><button data-shop-tab="jade">仙玉</button><button data-shop-tab="packs">礼包</button><button data-shop-tab="monthly">月卡</button><button data-shop-tab="growth">成长</button><button data-shop-tab="vip">VIP</button></nav><div id="uiShopToast" class="ui-shop-toast hidden"></div><div id="uiShopContent" class="ui-shop-content"></div></section>`;document.body.appendChild(o);$('uiShopClose').onclick=closeShop;o.onclick=e=>{if(e.target===o)closeShop()};o.querySelectorAll('[data-shop-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.shopTab;renderShop()});return o}
function walletHtml(w){const lv=vipLevel(w.vipExp);return `<div><span>仙玉</span><b>${Math.floor(w.jade)}</b></div><div><span>VIP</span><b>VIP ${lv}</b></div><div><span>月卡</span><b>${monthlyDays(w)?monthlyDays(w)+'天':'未开'}</b></div>`}
function packCard(pack,w,s,reason=''){const sold=!canBuyPack(pack,w,s),price=pack.jadePrice?`${pack.jadePrice}仙玉`:`模拟 ¥${pack.price}`;return `<button class="ui-pack-card ${pack.id==='vip8-sprint'?'node':''}" data-pack="${pack.id}" ${sold?'disabled':''}><span>${esc(reason||pack.tag)}</span><b>${esc(pack.name)}</b><small>${esc(pack.desc)}</small><em>${esc(rewardText(pack.reward))}</em><strong>${sold?'本期已购':price}</strong></button>`}
function renderRecommend(w){const s=gameState(),p=s?.player||{},ids=relevantPackIds(),lv=vipLevel(w.vipExp),life=p.lifespan?Math.max(0,p.lifespan-age(s)):null;const reason=id=>id==='stone-rescue'?'检测到灵石偏低':id==='injury-rescue'?'检测到当前受伤':id==='break-18'?'修为接近瓶颈':id==='revenge-12'?'检测到战败记录':id==='realm-30'?'当前境界专属':id==='sect-30'?'已加入宗门':id==='vip8-sprint'?'你已经站在VIP8门口':'商行强推';return `<div class="ui-shop-node"><span>当前氪金路线</span><b>${esc(nodeCopy(lv,w))}</b><small>${life!=null?`剩余寿元约 ${life} 年 · `:''}商城会根据你当前缺口改变推荐。</small></div><div class="ui-pack-grid">${ids.map(id=>packCard(PACKS.find(x=>x.id===id),w,s,reason(id))).join('')}</div>`}
function renderJade(w){return `<div class="ui-shop-section-title"><span>仙玉充值</span><b>每档首购额外再送基础仙玉</b></div><div class="ui-recharge-grid">${RECHARGE.map(x=>{const first=!w.firstBonusUsed[x.id],gain=x.base+x.bonus+(first?x.base:0);return `<button class="ui-recharge-card" data-recharge="${x.id}"><span>${first?'首购双倍':'常规充值'}</span><b>${gain}</b><small>仙玉</small><em>模拟 ¥${x.price}</em></button>`}).join('')}</div><div class="ui-shop-footnote">充值本身主要负责仙玉和VIP经验；仙玉可以继续买资源礼包。</div>`}
function renderPacks(w){const s=gameState();return `<div class="ui-shop-section-title"><span>礼包中心</span><b>每日 / 状态触发 / 仙玉消费</b></div><div class="ui-pack-grid">${PACKS.filter(x=>x.id!=='vip8-sprint'||vipLevel(w.vipExp)===7).map(x=>packCard(x,w,s)).join('')}</div>`}
function renderMonthly(w){const days=monthlyDays(w),can=days>0&&w.monthlyClaimDate!==today();return `<div class="ui-premium-hero"><span>玄玉月契</span><h3>${days?`剩余 ${days} 天`:'尚未开通'}</h3><p>模拟 ¥30：立即300仙玉，30天内每日100仙玉，同时累计300 VIP经验。</p><button class="primary" data-monthly-buy>${days?'续期30天':'模拟开通 ¥30'}</button></div><div class="ui-daily-claim"><div><span>今日月卡</span><b>${days?'100仙玉':'未开通'}</b></div><button data-monthly-claim ${can?'':'disabled'}>${w.monthlyClaimDate===today()?'已领取':days?'领取':'未开'}</button></div>`}
function renderGrowth(w){const ri=Number(gameState()?.player?.realmIndex)||0,done=new Set(w.growthClaimed);return `<div class="ui-premium-hero growth"><span>问道成长令</span><h3>${w.growthOwned?'已激活':'一次购买 · 全程返还'}</h3><p>模拟 ¥68：立即680仙玉，此后境界越高返还越多。</p>${w.growthOwned?'<button disabled>已拥有</button>':'<button class="primary" data-growth-buy>模拟购买 ¥68</button>'}</div><div class="ui-growth-list">${GROWTH.map(x=>{const unlock=ri>=x.realm,claimed=done.has(x.id);return `<div class="ui-growth-row ${unlock?'unlocked':''}"><div><span>${x.name}</span><small>${unlock?'境界已达成':'尚未达到'}</small></div><b>${x.jade}仙玉</b><button data-growth-claim="${x.id}" ${w.growthOwned&&unlock&&!claimed?'':'disabled'}>${claimed?'已领':w.growthOwned&&unlock?'领取':'未解锁'}</button></div>`}).join('')}</div>`}
function renderVip(w){const lv=vipLevel(w.vipExp),next=VIP_THRESHOLDS[lv+1],progress=next?Math.min(100,(w.vipExp-VIP_THRESHOLDS[lv])/(next-VIP_THRESHOLDS[lv])*100):100,claimed=new Set(w.vipMilestoneClaimed),gift=VIP_DAILY[lv]||0;return `<div class="ui-vip-card ${lv===8?'vip8':''}"><span>当前等级</span><h3>VIP ${lv}</h3><p>累计模拟充值 ¥${Number(w.totalCny||0).toFixed(0)} · VIP经验 ${Math.floor(w.vipExp)}${next?` / ${next}`:''}</p><div class="ui-vip-progress"><i style="width:${progress}%"></i></div><strong>${esc(nodeCopy(lv,w))}</strong></div><div class="ui-daily-claim"><div><span>VIP每日礼</span><b>${lv?gift+'仙玉':'VIP1解锁'}</b></div><button data-vip-daily ${lv&&w.vipClaimDate!==today()?'':'disabled'}>${w.vipClaimDate===today()?'今日已领':'领取'}</button></div><div class="ui-vip-milestones">${Array.from({length:15},(_,i)=>i+1).map(n=>{const r=VIP_REWARDS[n],unlock=lv>=n,done=claimed.has(n);return `<div class="ui-vip-level ${n===8||n===12||n===15?'node':''} ${unlock?'active':''}"><div><b>VIP ${n}${n===8?' · 大节点':n===12||n===15?' · 大奖':''}</b><small>${esc(rewardText(r))}</small></div><button data-vip-milestone="${n}" ${unlock&&!done?'':'disabled'}>${done?'已领取':unlock?'领取':'未达成'}</button></div>`}).join('')}</div><button class="ui-reset-premium" data-premium-reset>重置模拟付费数据</button>`}
function renderShop(){const o=ensureOverlay(),w=load();$('uiShopWallet').innerHTML=walletHtml(w);o.querySelectorAll('[data-shop-tab]').forEach(b=>b.classList.toggle('active',b.dataset.shopTab===activeTab));$('uiShopContent').innerHTML=activeTab==='recommend'?renderRecommend(w):activeTab==='jade'?renderJade(w):activeTab==='packs'?renderPacks(w):activeTab==='monthly'?renderMonthly(w):activeTab==='growth'?renderGrowth(w):renderVip(w);bindActions()}
function toast(t){const e=$('uiShopToast');if(!e)return;e.textContent=t;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),2200)}
function paid(w,price,label,reward={}){w.vipExp+=price*10;w.totalCny+=price;if(reward.jade)w.jade+=reward.jade;addReceipt(w,label);grantGame(reward);save(w)}
function simulateRecharge(id){const x=RECHARGE.find(r=>r.id===id);if(!x)return;const w=load(),first=!w.firstBonusUsed[id],gain=x.base+x.bonus+(first?x.base:0);w.jade+=gain;w.vipExp+=x.price*10;w.totalCny+=x.price;w.firstBonusUsed[id]=true;addReceipt(w,`充值¥${x.price} · 仙玉+${gain}`);save(w);renderShop();toast(`仙玉 +${gain} · VIP经验 +${x.price*10}`)}
function buyPack(id){const pack=PACKS.find(x=>x.id===id),w=load(),s=gameState();if(!pack||!canBuyPack(pack,w,s))return;if(pack.jadePrice){if(w.jade<pack.jadePrice)return toast('仙玉不足');w.jade-=pack.jadePrice;if(pack.reward.jade)w.jade+=pack.reward.jade;grantGame(pack.reward);addReceipt(w,`${pack.name} · ${pack.jadePrice}仙玉`)}else paid(w,pack.price,`${pack.name} · ¥${pack.price}`,pack.reward);w.packBuys[packKey(pack,s)]=1;save(w);renderShop();toast(`${pack.name} 已到账`)}
function buyMonthly(){const w=load(),base=Math.max(Date.now(),Number(w.monthlyUntil)||0);w.monthlyUntil=base+30*86400000;w.jade+=300;w.vipExp+=300;w.totalCny+=30;addReceipt(w,'玄玉月契 ¥30');save(w);renderShop();toast('月卡 +30天 · 仙玉+300')}
function claimMonthly(){const w=load();if(monthlyDays(w)<=0||w.monthlyClaimDate===today())return;w.monthlyClaimDate=today();w.jade+=100;save(w);renderShop();toast('月卡仙玉 +100')}
function buyGrowth(){const w=load();if(w.growthOwned)return;w.growthOwned=true;w.jade+=680;w.vipExp+=680;w.totalCny+=68;addReceipt(w,'问道成长令 ¥68');save(w);renderShop();toast('成长令已激活')}
function claimGrowth(id){const x=GROWTH.find(a=>a.id===id),w=load();if(!x||!w.growthOwned||(Number(gameState()?.player?.realmIndex)||0)<x.realm||w.growthClaimed.includes(id))return;w.growthClaimed.push(id);w.jade+=x.jade;save(w);renderShop();toast(`${x.name} · 仙玉+${x.jade}`)}
function claimVipDaily(){const w=load(),lv=vipLevel(w.vipExp),gift=VIP_DAILY[lv]||0;if(!gift||w.vipClaimDate===today())return;w.vipClaimDate=today();w.jade+=gift;save(w);renderShop();toast(`VIP${lv}每日礼 · 仙玉+${gift}`)}
function claimVipMilestone(n){n=Number(n);const w=load(),lv=vipLevel(w.vipExp),r=VIP_REWARDS[n];if(!r||lv<n||w.vipMilestoneClaimed.includes(n))return;w.vipMilestoneClaimed.push(n);if(r.jade)w.jade+=r.jade;if(r.title&&!w.titles.includes(r.title))w.titles.push(r.title);grantGame(r);save(w);renderShop();toast(n===8?'VIP8大节点奖励已全部到账':`VIP${n}奖励已到账`)}
function resetPremium(){if(!confirm('只清除模拟充值、仙玉、VIP、礼包数据，不删除游戏存档。确认？'))return;localStorage.removeItem(KEY);renderShop();toast('模拟付费数据已重置')}
function bindActions(){document.querySelectorAll('[data-recharge]').forEach(b=>b.onclick=()=>simulateRecharge(b.dataset.recharge));document.querySelectorAll('[data-pack]').forEach(b=>b.onclick=()=>buyPack(b.dataset.pack));document.querySelector('[data-monthly-buy]')?.addEventListener('click',buyMonthly);document.querySelector('[data-monthly-claim]')?.addEventListener('click',claimMonthly);document.querySelector('[data-growth-buy]')?.addEventListener('click',buyGrowth);document.querySelectorAll('[data-growth-claim]').forEach(b=>b.onclick=()=>claimGrowth(b.dataset.growthClaim));document.querySelector('[data-vip-daily]')?.addEventListener('click',claimVipDaily);document.querySelectorAll('[data-vip-milestone]').forEach(b=>b.onclick=()=>claimVipMilestone(b.dataset.vipMilestone));document.querySelector('[data-premium-reset]')?.addEventListener('click',resetPremium)}
function openShop(tab='recommend'){activeTab=tab;ensureOverlay().classList.remove('hidden');document.body.classList.add('ui-shop-open');renderShop()}
function closeShop(){$('uiShopOverlay')?.classList.add('hidden');document.body.classList.remove('ui-shop-open')}
function renderOfferChip(){const s=gameState(),w=load(),host=$('uiFinalRumor')?.parentElement;if(!host||!s?.player)return;let chip=$('uiContextOffer');const id=relevantPackIds().find(x=>!['daily-6','flash-68','jade-188'].includes(x))||'flash-68',pack=PACKS.find(x=>x.id===id);if(!pack)return;if(!chip){chip=document.createElement('button');chip.id='uiContextOffer';chip.className='ui-context-offer';host.appendChild(chip)}const lv=vipLevel(w.vipExp),reason=id==='vip8-sprint'?'VIP8大奖就在前面':id==='stone-rescue'?'灵石偏低，商行闻着味来了':id==='injury-rescue'?'你受伤了，礼包立刻出现':id==='break-18'?'快到瓶颈，推你一把':id==='revenge-12'?'刚有败绩，翻盘包上架':id==='realm-30'?'境界礼包正在等你':'今日限时重氪箱';chip.innerHTML=`<span>${esc(reason)}</span><b>${esc(pack.name)}</b><em>${pack.jadePrice?pack.jadePrice+'仙玉':'模拟 ¥'+pack.price}</em><i>›</i>`;chip.onclick=()=>openShop('recommend');chip.classList.toggle('vip8',lv===7)}
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeShop()});window.addEventListener('DOMContentLoaded',()=>{ensureOverlay();let n=0;const t=setInterval(()=>{n++;updateCurrency();renderOfferChip();if(window.__TAIXUAN_TEST__||n>100)clearInterval(t)},100);for(const id of ['spiritStoneQuick','hpQuick','realmName','cultivationText']){const el=$(id);if(el)new MutationObserver(()=>{updateCurrency();renderOfferChip()}).observe(el,{childList:true,subtree:true,characterData:true})}});
window.__TAIXUAN_SHOP__={open:openShop,close:closeShop,getWallet:()=>JSON.parse(JSON.stringify(load())),vipLevel:()=>vipLevel(load().vipExp),reset:()=>{localStorage.removeItem(KEY);updateCurrency();renderOfferChip()}};
})();
