window.__TAIXUAN_PATCH_V03__=function(src){
  const must=(pattern,replacement,label)=>{const next=src.replace(pattern,replacement);if(next===src)throw new Error('V0.3升级失败：'+label+' 未命中');src=next};
  must("const SAVE_KEY='xiuxian_world_v02'; const OLD_KEY='xiuxian_world_v01'; const VERSION='0.2.0';","const SAVE_KEY='xiuxian_world_v02'; const OLD_KEY='xiuxian_world_v01'; const VERSION='0.3.0';",'版本号');
  must(/const ENEMIES=\[[\s\S]*?\];\nfunction rand/,`const ENEMIES=[
 {name:'灰背野狼',kind:'野兽',realm:0,hp:46,atk:[5,9],reward:{stones:[0,1],herbs:[0,1],rep:0},weight:34,areas:['青石村','青石镇']},
 {name:'山道劫匪',kind:'凡人',realm:0,hp:58,atk:[6,11],reward:{stones:[1,4],herbs:[0,0],rep:1},weight:30,areas:['青石镇','临江城']},
 {name:'铁背狼妖',kind:'妖兽',realm:1,hp:82,atk:[9,15],reward:{stones:[2,5],herbs:[1,2],rep:2},weight:28,areas:['青石镇','黑风岭']},
 {name:'血刀门探子',kind:'修士',realm:2,hp:104,atk:[11,18],reward:{stones:[3,7],herbs:[0,1],rep:3},weight:18,areas:['临江城','黑风岭']},
 {name:'黑风岭狼妖',kind:'妖兽',realm:2,hp:112,atk:[12,19],reward:{stones:[3,6],herbs:[1,3],rep:3},weight:25,areas:['黑风岭']},
 {name:'青鳞妖蛇',kind:'妖兽',realm:3,hp:138,atk:[15,23],reward:{stones:[5,9],herbs:[2,4],rep:4},weight:16,areas:['黑风岭']},
 {name:'黑风岭狼王',kind:'妖兽',realm:4,hp:168,atk:[19,29],reward:{stones:[8,14],herbs:[3,5],rep:7},weight:8,areas:['黑风岭']}
];
function rand`,'敌人表');
  must(/function weightedEnemy\(\)\{[\s\S]*?\}\nfunction dayNumber/,`function weightedEnemy(){const pool=ENEMIES.filter(e=>!e.areas||e.areas.includes(state.player.location));const rows=pool.map(e=>({e,w:e.weight/(1+Math.abs(e.realm-state.player.realmIndex)*.65)}));let n=rand()*rows.reduce((a,x)=>a+x.w,0);for(const x of rows){n-=x.w;if(n<=0)return x.e}return rows[0]?.e||ENEMIES[0]}
function dangerLabel(e){const d=(e.realm||0)-state.player.realmIndex;return d<=-2?'碾压':d===-1?'优势':d===0?'势均力敌':d===1?'危险':d===2?'极危':'九死一生'}
function injuryLabel(){return ['无伤','轻伤','重伤','濒死'][clamp(state.player.injury||0,0,3)]}
function deathRisk(e){const d=(e.realm||0)-state.player.realmIndex,inj=state.player.injury||0;if(d<2&&inj<3)return 0;return clamp((d>=2?.04+d*.045:0)+inj*.035,0,.32)}
function dayNumber`,'遇敌算法');
  must("diligence:0,insight:0,hp:70,qi:0}","diligence:0,insight:0,hp:70,qi:0,injury:0,battleWins:0,battleLosses:0,kills:0}",'新角色战斗字段');
  must("if(state.player.qi==null)state.player.qi=maxQi();","if(state.player.qi==null)state.player.qi=maxQi();if(state.player.injury==null)state.player.injury=0;if(state.player.battleWins==null)state.player.battleWins=0;if(state.player.battleLosses==null)state.player.battleLosses=0;if(state.player.kills==null)state.player.kills=0;",'旧存档迁移');
  must("const gain=Math.max(1,Math.floor(base*rootM*manualM*cheatM));","const injuryM=[1,.90,.70,.48][clamp(state.player.injury||0,0,3)];const gain=Math.max(1,Math.floor(base*rootM*manualM*cheatM*injuryM));",'伤势影响修炼');
  must(/function rest\(\)\{[\s\S]*?\}\nfunction rumor/,`function rest(){advanceDays(1);const before=state.player.hp,old=state.player.injury||0;state.player.hp=Math.min(maxHp(),state.player.hp+Math.ceil(maxHp()*.52));state.player.qi=maxQi();if(state.player.injury>0)state.player.injury--;addDiligence(1);addPersonal('你闭门休息了一整日，气血与灵力恢复。'+(old>state.player.injury?'伤势有所缓解。':''),'good');save();render();showResult('闭门休整',\`气血 +\${state.player.hp-before}\\n灵力恢复至满值\${old>state.player.injury?\`\\n伤势：\${['无伤','轻伤','重伤','濒死'][old]} → \${injuryLabel()}\`:''}\`,'good')}
function rumor`,'休整疗伤');
  must(/function explore\(\)\{[\s\S]*?\n\}\nfunction startMinorEvent/,`function explore(){advanceDays(1);addDiligence(2);const danger=state.player.location==='黑风岭'?.46:(state.player.location==='临江城'||state.player.location==='青石镇')?.30:.20;const x=rand();if(x<danger){startCombat(weightedEnemy());return}if(x<danger+.30){startMinorEvent();return}if(x<danger+.46){const n=rint(1,4);state.player.spiritStones+=n;addPersonal(\`你在一处废弃石缝里发现 \${n} 块灵石。\`,'good');save();render();showResult('意外收获',\`你找到了一只破布袋。\\n灵石 +\${n}\`,'good');return}addPersonal('你在附近转了一圈，没有碰见特别的事。');save();render();showResult('附近探索','这一日风平浪静。修真界并不是每天都有奇遇。')}
function startMinorEvent`,'地区危险度');
  must(/function startCombat\(enemyTemplate\)[\s\S]*?\nfunction majorDef/,`function startCombat(enemyTemplate){const e=JSON.parse(JSON.stringify(enemyTemplate));if(!e.reward)e.reward={stones:[0,0],herbs:[0,0],rep:0};if(!e.reward.herbs)e.reward.herbs=[0,0];combat={enemy:e,enemyHp:e.hp,playerHp:state.player.hp,playerQi:state.player.qi,defending:false,evade:0,round:1,logs:[\`你遭遇了\${e.name}。危险判断：\${dangerLabel(e)}。\`]};renderCombat()}
function renderCombat(){const e=combat.enemy,pPct=clamp(combat.playerHp/maxHp()*100,0,100),ePct=clamp(combat.enemyHp/e.hp*100,0,100),wind='御风步'in state.player.spells;let html=\`<h2>遭遇战 · 第\${combat.round}回合</h2><div class="combatants"><div class="fighter"><b>\${esc(state.player.name)}</b><div class="hp">\${realm().name} · 气血 \${combat.playerHp}/\${maxHp()} · 灵力 \${combat.playerQi}/\${maxQi()}</div><div class="bar"><i style="width:\${pPct}%"></i></div></div><div class="vs">VS</div><div class="fighter"><b>\${esc(e.name)}</b><div class="hp">\${esc(e.kind||'敌人')} · \${REALMS[Math.min(e.realm||0,REALMS.length-1)].name} · \${dangerLabel(e)}</div><div class="hp">气血 \${Math.max(0,combat.enemyHp)}/\${e.hp}</div><div class="bar"><i style="width:\${ePct}%"></i></div></div></div><div class="combat-log">\${combat.logs.slice(-9).map(x=>\`• \${esc(x)}<br>\`).join('')}</div><div class="modal-actions two"><button data-combat="attack">拳脚攻击</button><button data-combat="spell" \${!('火弹术'in state.player.spells)||combat.playerQi<SPELLS['火弹术'].qi?'disabled':''}>火弹术</button><button data-combat="wind" \${!wind||combat.playerQi<SPELLS['御风步'].qi?'disabled':''}>御风步</button><button data-combat="defend">防御</button><button data-combat="flee">逃跑</button></div>\`;openModal(html,false);document.querySelectorAll('[data-combat]').forEach(b=>b.onclick=()=>combatAction(b.dataset.combat))}
function combatAction(a){if(!combat||state.flags.dead)return;const e=combat.enemy;combat.defending=false;if(a==='attack'){const prof=state.player.spells['基础拳脚']||0,dmg=rint(7,12)+state.player.realmIndex*3+Math.floor(prof/35)+Math.floor(state.player.manualProf/80);combat.enemyHp-=dmg;state.player.spells['基础拳脚']=prof+2;combat.logs.push(\`你近身攻出一击，造成 \${dmg} 点伤害。\`)}else if(a==='spell'){const sp=SPELLS['火弹术'];if(!('火弹术'in state.player.spells)||combat.playerQi<sp.qi)return;combat.playerQi-=sp.qi;const prof=state.player.spells['火弹术']||0,dmg=sp.power+rint(2,8)+state.player.realmIndex*4+Math.floor(prof/14);combat.enemyHp-=dmg;state.player.spells['火弹术']=prof+4;combat.logs.push(\`火弹炸开，造成 \${dmg} 点伤害。\`)}else if(a==='wind'){const sp=SPELLS['御风步'];if(!('御风步'in state.player.spells)||combat.playerQi<sp.qi)return;combat.playerQi-=sp.qi;const prof=state.player.spells['御风步']||0;state.player.spells['御风步']=prof+3;combat.evade=2;combat.logs.push('你运转御风步，接下来两回合更容易闪开攻击。')}else if(a==='defend'){combat.defending=true;combat.logs.push('你收敛气息，架势转守。')}else if(a==='flee'){const diff=(e.realm||0)-state.player.realmIndex,windBonus=('御风步'in state.player.spells)?Math.min(.30,(state.player.spells['御风步']||0)/180):0,chance=clamp(.40+windBonus-diff*.08,.12,.78);if(rand()<chance){state.player.hp=Math.max(1,combat.playerHp);state.player.qi=combat.playerQi;addPersonal(\`你从\${e.name}手中脱身。\`);combat=null;save();render();closeModal();showResult('成功脱身','你没有继续纠缠。');return}else combat.logs.push('你试图脱身，但被对方逼了回来。')}if(combat.enemyHp<=0){finishCombat(true);return}let dodged=false;if(combat.evade>0){combat.evade--;const prof=state.player.spells['御风步']||0;if(rand()<clamp(.34+prof/500,0,.62)){dodged=true;combat.logs.push(\`御风步生效，你避开了\${e.name}的反击。\`)}}if(!dodged){let edmg=rint(e.atk[0],e.atk[1]);if(combat.enemyHp/e.hp<.32&&rand()<.30){edmg=Math.ceil(edmg*1.35);combat.logs.push(\`\${e.name}在伤势刺激下突然暴起！\`)}if(combat.defending)edmg=Math.ceil(edmg*.52);edmg=Math.max(1,edmg-Math.floor(state.player.realmIndex*.8));combat.playerHp-=edmg;combat.logs.push(\`\${e.name}反击，造成 \${edmg} 点伤害。\`)}if(combat.playerHp<=0){finishCombat(false);return}combat.round++;renderCombat()}
function finishCombat(win){const e=combat.enemy;if(win){const stones=rint(e.reward.stones?.[0]||0,e.reward.stones?.[1]||0),herbs=rint(e.reward.herbs?.[0]||0,e.reward.herbs?.[1]||0);state.player.spiritStones+=stones;state.player.herbs+=herbs;state.player.reputation+=e.reward.rep||0;state.player.hp=Math.max(1,combat.playerHp);state.player.qi=combat.playerQi;state.player.battleWins++;state.player.kills++;addDiligence(3);addPersonal(\`你击败\${e.name}。\${stones?\`获得\${stones}块灵石。\`:''}\${herbs?\`获得\${herbs}株灵草。\`:''}\`,'good');combat=null;closeModal();save();render();showResult('战斗胜利',\`\${stones?\`灵石 +\${stones}\\n\`:''}\${herbs?\`灵草 +\${herbs}\\n\`:''}\${e.reward.rep?\`声望 +\${e.reward.rep}\\n\`:''}战绩 \${state.player.battleWins}胜 \${state.player.battleLosses}败\`,'good')}else{state.player.battleLosses++;const risk=deathRisk(e);if(risk>0&&rand()<risk){state.flags.dead=true;state.player.hp=0;state.player.qi=0;addPersonal(\`你败在\${e.name}手中，伤势过重，身死道消。\`,'bad');combat=null;closeModal();save();render();showResult('身死道消',\`敌人：\${e.name}\\n此世已经结束。\`,'bad');return}const diff=Math.max(0,(e.realm||0)-state.player.realmIndex),add=diff>=2?2:1;state.player.injury=clamp((state.player.injury||0)+add,0,3);const lost=Math.min(state.player.spiritStones,rint(0,Math.max(2,diff+1)));state.player.spiritStones-=lost;state.player.hp=Math.max(1,Math.ceil(maxHp()*(state.player.injury>=3?.18:.30)));state.player.qi=0;addPersonal(\`你败在\${e.name}手下，拖着\${injuryLabel()}逃了回来。\`,'bad');combat=null;closeModal();save();render();showResult('战斗失败',\`你侥幸活了下来。\\n当前伤势：\${injuryLabel()}\${lost?\`\\n遗失灵石 \${lost}\`:''}\\n建议先闭门休整。\`,'bad')}}
function majorDef`,'战斗闭环');
  must("$('heroSub').textContent=`${age()}岁 · ${season()} · ${state.player.location} · ${root().name}`;","$('heroSub').textContent=`${age()}岁 · ${season()} · ${state.player.location} · ${root().name}${state.player.injury?` · ${injuryLabel()}`:''}`;",'首页伤势');
  must(/function renderCharacter\(\)\{[\s\S]*?\nfunction renderMap/,`function renderCharacter(){const p=state.player;$('characterStats').innerHTML=\`<div class="kv"><span>姓名</span><b>\${esc(p.name)}</b></div><div class="kv"><span>年龄 / 寿元</span><b>\${age()} / \${p.lifespan}</b></div><div class="kv"><span>境界</span><b>\${realm().name}</b></div><div class="kv"><span>气血</span><b>\${p.hp} / \${maxHp()}</b></div><div class="kv"><span>灵力</span><b>\${p.qi} / \${maxQi()}</b></div><div class="kv"><span>伤势</span><b>\${injuryLabel()}</b></div><div class="kv"><span>所在地</span><b>\${p.location}</b></div><div class="kv"><span>声望</span><b>\${p.reputation}</b></div><div class="kv"><span>战绩</span><b>\${p.battleWins}胜 / \${p.battleLosses}败 · 击杀\${p.kills}</b></div>\`;$('rootInfo').innerHTML=\`<div class="skill-card"><div class="skill-head"><b>\${root().name}</b><span>修炼倍率 ×\${root().mult.toFixed(2)}</span></div><div class="skill-desc">\${root().desc}</div></div>\`;$('manualList').innerHTML=\`<div class="skill-card"><div class="skill-head"><b>《\${esc(p.manual)}》</b><span>\${manual().quality}</span></div><div class="skill-desc">熟练度 \${p.manualProf} · 功法倍率 ×\${manual().mult.toFixed(2)}<br>\${manual().desc}</div></div>\`;$('spellList').innerHTML=Object.entries(p.spells).map(([name,prof])=>{const s=SPELLS[name]||{quality:'未知',desc:''};return \`<div class="skill-card"><div class="skill-head"><b>\${esc(name)}</b><span>\${s.quality}</span></div><div class="skill-desc">熟练度 \${prof}\${s.qi?\` · 消耗灵力 \${s.qi}\`:''}<br>\${s.desc}</div></div>\`}).join('')}
function renderMap`,'角色战绩');
  must("document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>({cultivate,gather,work,explore,rumor,rest}[b.dataset.action])());","document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if(state?.flags?.dead)return showResult('此世已终','你已经身死道消，请重新开局。','bad');({cultivate,gather,work,explore,rumor,rest}[b.dataset.action])()});",'死亡后行动锁');
  if(!src.includes("const VERSION='0.3.0'"))throw new Error('V0.3升级失败：最终版本断言');
  return src;
};
