import fs from 'fs';import assert from 'assert';import {JSDOM} from 'jsdom';
const INDEX_PATH=process.env.INDEX_PATH||'index.html',GAME_PATH=process.env.GAME_PATH||'src/game-v38.js',SAVE_KEY='xiuxian_world_v02';const htmlRaw=fs.readFileSync(INDEX_PATH,'utf8'),source=fs.readFileSync(GAME_PATH,'utf8');assert(source.includes("const VERSION='3.8.0'"));assert(source.includes('const SAVE_SCHEMA_VERSION=35'));for(const x of ['大乘初期','大乘圆满','v38ContemplateOrigin','v38TemperNatalOrigin','v38PrepareTribulation','v38StartWorldCrisis','v38ActivateWorldEdict'])assert(source.includes(x),x);
function cleanHtml(h){return h.replace(/<script[^>]+src=["'][^"']*app\.js[^"']*["'][^>]*><\/script>/i,'')}function makeDom(seed=null){const d=new JSDOM(cleanHtml(htmlRaw),{url:'http://example.test/',runScripts:'outside-only',pretendToBeVisual:true});d.window.matchMedia=()=>({matches:false,addListener(){},removeListener(){}});d.window.scrollTo=()=>{};d.window.console=console;if(seed!==null)d.window.localStorage.setItem(SAVE_KEY,seed);d.window.eval(source);return d}function fresh(){const d=makeDom(),api=d.window.__TAIXUAN_TEST__;api.newGame('V38回归');return {d,api}}function loadState(o){const d=makeDom(JSON.stringify(o));d.window.document.getElementById('continueBtn').click();return d}function stripV38(s){for(const k of ['v38MahayanaVersion','v38OriginInsight','v38WorldAuthority','v38OriginBacklash','v38MahayanaFailures','v38OriginActions','v38WorldCrisisWins','v38WorldEdictUses','v38NatalOriginMarks','mahayanaEssence','v38TribulationPrep'])delete s.player[k];for(const k of ['v38WorldOrder','v38CrisisCycle','v38CrisisStatus','v38ActiveCrisisId','v38CrisisEvents','v38LastCrisisResult','v38PowerStanding'])delete s.world[k]}
let {api}=fresh();for(const fn of ['v38WorldPowerRegistry','v38WorldActorRegistry','v38CrisisRegistry','v38ContemplateOrigin','v38ExerciseWorldAuthority','v38CraftMahayanaEssence','v38TemperNatalOrigin','v38TribulationPrepSnapshot','v38PrepareTribulation','v38AttemptMahayanaBreakthrough','v38MinorGate','v38ActivateWorldEdict','v38StartWorldCrisis','v38JoinWorldCrisis','v38WorldSnapshot','v38CatalogSnapshot','v38StateSnapshot','v38SetPlayerForTest','v37StateSnapshot','v36StateSnapshot'])assert.equal(typeof api[fn],'function',fn);
let s=api.getState();assert.equal(s.version,'3.8.0');assert.equal(s.saveSchemaVersion,35);assert.equal(s.player.contentStateVersion,9);let cat=api.v38CatalogSnapshot();assert.deepEqual({realms:cat.realms,regions:cat.regions,routes:cat.routes,materials:cat.materials,recipes:cat.recipes,manuals:cat.manuals,spells:cat.spells,equipment:cat.equipment,artifacts:cat.artifacts,enemies:cat.enemies,auctionPool:cat.auctionPool,worldPowers:cat.worldPowers,crises:cat.crises},{realms:38,regions:24,routes:38,materials:84,recipes:48,manuals:40,spells:96,equipment:84,artifacts:48,enemies:84,auctionPool:24,worldPowers:4,crises:3});const reg=api.contentRegistrySnapshot();assert.equal(reg.registryVersion,9);assert.equal(reg.counts.worldPowers,4);assert.equal(reg.counts.worldActors,6);assert.equal(reg.counts.worldCrises,3);assert.equal(Object.keys(reg.worldActors).length,6);
// schema34 -> 35 preserves V3.7 law/unity and V3.6 space.
let old=api.getState();old.version='3.7.0';old.saveSchemaVersion=34;old.player.contentStateVersion=8;old.player.v37LawId='law-severing';old.player.v37LawProficiency=177;old.player.v37Unity=109;old.player.v36SpaceInsight=61;stripV38(old);let od=loadState(old),oa=od.window.__TAIXUAN_TEST__,os=oa.getState();assert.equal(os.version,'3.8.0');assert.equal(os.saveSchemaVersion,35);assert.equal(os.player.v37LawId,'law-severing');assert.equal(os.player.v37LawProficiency,177);assert.equal(os.player.v37Unity,109);assert.equal(os.player.v36SpaceInsight,61);assert.equal(os.player.v38OriginInsight,0);assert.equal(os.world.v38WorldOrder,55);
// Origin insight is an independent post-unity axis.
oa.v38SetPlayerForTest({realmIndex:33,location:'界源海',lawProficiency:190,unity:115});let og=oa.v38ContemplateOrigin(50);assert.equal(og.ok,true);assert.equal(oa.v38StateSnapshot().originInsight,50);oa.v38SetPlayerForTest({realmIndex:34,location:'人界议庭'});let au=oa.v38ExerciseWorldAuthority(30);assert.equal(au.ok,true);assert.equal(oa.v38StateSnapshot().worldAuthority,30);
// Natal artifact must carry real origin marks; major Mahayana breakthrough requires it plus origin essence.
let st=oa.getState();st.player.natalArtifactId='artifact-v37-lawcleaver-sword';st.player.equipmentInventory['artifact-v37-lawcleaver-sword']={itemId:'item-v37-lawcleaver-sword',artifactId:'artifact-v37-lawcleaver-sword',refinement:5,warmth:300,damaged:false,originMarks:0};assert.equal(oa.v38TemperNatalOrigin(true).ok,true);assert.equal(oa.v38StateSnapshot().natalOriginMarks,1);for(let i=0;i<5;i++)assert.equal(oa.v38CraftMahayanaEssence(true).ok,true);oa.v38SetPlayerForTest({realmIndex:33,location:'天穹祖脉',originInsight:55,authority:30,lawProficiency:195,unity:115,mahayanaEssence:5,natalMarks:1,insight:50,progressFull:true});let br=oa.v38AttemptMahayanaBreakthrough('success');assert.equal(br.outcome,'success');s=oa.getState();assert.equal(s.player.realmIndex,34);assert(s.player.lifespan>=25000);assert(s.player.v38WorldAuthority>=25);
// Major failure is materially harsher than ordinary failure and can damage natal origin state.
oa.newGame('V38失败回归');st=oa.getState();st.player.natalArtifactId='artifact-v37-lawcleaver-sword';st.player.equipmentInventory['artifact-v37-lawcleaver-sword']={itemId:'item-v37-lawcleaver-sword',artifactId:'artifact-v37-lawcleaver-sword',refinement:6,warmth:400,damaged:false,originMarks:2};oa.v38SetPlayerForTest({realmIndex:33,location:'天穹祖脉',originInsight:60,authority:35,lawProficiency:200,unity:118,mahayanaEssence:5,natalMarks:2,insight:50,progressFull:true});let life0=oa.getState().player.lifespan;let fail=oa.v38AttemptMahayanaBreakthrough('fail');assert.equal(fail.outcome,'failure');s=oa.getState();assert.equal(s.player.realmIndex,33);assert.equal(s.player.injury,3);assert.equal(s.player.v37LawProficiency,190);assert.equal(s.player.v37Unity,106);assert.equal(s.player.v38OriginInsight,52);assert(s.player.lifespan<life0);assert.equal(s.player.equipmentInventory['artifact-v37-lawcleaver-sword'].damaged,true);assert.equal(s.player.v38NatalOriginMarks,1);
// Minor Mahayana realms require origin, authority AND natal-origin marks.
oa.v38SetPlayerForTest({realmIndex:34,originInsight:80,authority:39,natalMarks:2});assert.equal(oa.v38MinorGate(34).ok,false);oa.v38SetPlayerForTest({authority:40});assert.equal(oa.v38MinorGate(34).ok,true);
// World crisis has persistent consequences for world order, authority, power standing and sect resources.
oa.newGame('V38世界回归');oa.v38SetPlayerForTest({realmIndex:34,location:'界源海',originInsight:80,authority:30,lawProficiency:190,unity:115});st=oa.getState();st.player.sect='青云宗';const c0=st.player.sectContribution,order0=st.world.v38WorldOrder;let cs=oa.v38StartWorldCrisis('crisis-origin-tide');assert.equal(cs.ok,true);assert(oa.v38WorldSnapshot().worldOrder<order0);let cr=oa.v38JoinWorldCrisis('crisis-origin-tide','win');assert.equal(cr.ok,true);assert.equal(oa.v38WorldSnapshot().lastResult,'victory');assert(oa.v38WorldSnapshot().worldOrder>order0);assert(oa.getState().player.sectContribution>c0);assert(oa.v38StateSnapshot().worldCrisisWins>=1);
// World Edict is a real combat state, not a display-only stat.
oa.v38SetPlayerForTest({realmIndex:35,location:'界源海',originInsight:120,authority:70});oa.startCombat('界源幽灵');assert.equal(oa.v38ActivateWorldEdict(true),true);let comb=oa.getCombat();assert(comb.v38WorldEdictTurns>=3);const hp0=comb.enemyHp;oa.combatAction('attack');comb=oa.getCombat();assert(comb===null||comb.enemyHp<hp0);if(comb)assert(comb.v38WorldEdictTurns<3);
// V3.8 only opens tribulation preparation; it does not execute the V3.9 tribulation finale.
oa.v38SetPlayerForTest({realmIndex:36,location:'九霄劫台',originInsight:230,authority:145,natalMarks:6});for(const k of ['body','soul','law','artifact','formation'])assert.equal(oa.v38PrepareTribulation(k,true).ok,true);let prep=oa.v38TribulationPrepSnapshot();assert.equal(prep.unlocked,true);assert(prep.total>=60);assert(!source.includes('v39AttemptTribulation'));
// V3.7 law/domain and V3.6 space remain live.
assert.equal(oa.v37StateSnapshot().lawId===null||typeof oa.v37StateSnapshot().lawId==='string',true);assert('spaceInsight'in oa.v36StateSnapshot());
// Save/reload preserves origin, authority, world order, natal marks and tribulation preparation.
const saved=oa.getState(),rd=loadState(saved),ra=rd.window.__TAIXUAN_TEST__,rs=ra.getState();assert.equal(rs.saveSchemaVersion,35);assert.equal(rs.player.v38OriginInsight,230);assert.equal(rs.player.v38WorldAuthority,145);assert.equal(rs.player.v38NatalOriginMarks,6);assert(rs.player.v38TribulationPrep.body>=12);assert.equal(typeof rs.world.v38WorldOrder,'number');
// future schema36 is protected.
const future=ra.getState();future.saveSchemaVersion=36;future.version='future-v38';const raw=JSON.stringify(future),fd=makeDom(raw);fd.window.document.getElementById('continueBtn').click();assert.equal(fd.window.localStorage.getItem(SAVE_KEY),raw);assert.equal(fd.window.__TAIXUAN_TEST__.getState(),null);
console.log('V38_REGRESSION_PASS',JSON.stringify({version:'3.8.0',schema:35,realms:38,origin:true,authority:true,worldConsequences:true,worldActors:6,natalOrigin:true,tribulationPrepEntry:true,mahayanaBreakthrough:true,majorFailure:true,worldEdict:true,v37Preserved:true,v36Preserved:true,futureSaveProtected:true}));
