import fs from 'fs';
import assert from 'assert';
import {JSDOM} from 'jsdom';
const INDEX_PATH=process.env.INDEX_PATH||'index.html';const GAME_PATH=process.env.GAME_PATH||'src/game-v35.js';
const htmlRaw=fs.readFileSync(INDEX_PATH,'utf8'),source=fs.readFileSync(GAME_PATH,'utf8'),SAVE_KEY='xiuxian_world_v02';
assert(source.includes("const VERSION='3.5.0'"));assert(source.includes('const SAVE_SCHEMA_VERSION=32'));for(const x of ['V35_SHOPS','v35Trade','v35ApplyWarShock','v35SecretRealmTradeReward','renderV35EconomyPanel'])assert(source.includes(x),x);
function cleanHtml(h){return h.replace(/<script[^>]+src=["'][^"']*app\.js[^"']*["'][^>]*><\/script>/i,'')}
function makeDom(seed=null){const d=new JSDOM(cleanHtml(htmlRaw),{url:'http://example.test/',runScripts:'outside-only',pretendToBeVisual:true});d.window.matchMedia=()=>({matches:false,addListener(){},removeListener(){}});d.window.scrollTo=()=>{};d.window.console=console;if(seed!==null)d.window.localStorage.setItem(SAVE_KEY,seed);d.window.eval(source);return d}
function fresh(){const d=makeDom(),api=d.window.__TAIXUAN_TEST__;api.newGame('V35回归');return {d,api}}
function loadState(o){const d=makeDom(JSON.stringify(o));d.window.document.getElementById('continueBtn').click();return d}
function stripV35(s){for(const k of ['v35EconomyVersion','v35TradeLedger','v35NamedTrades','v35AuctionWins','v35RecipeTradeUnlocks','v35SecretRealmRecipes'])delete s.player[k];for(const k of ['v35StockByListing','v35StockCycle','v35AuctionCycle','v35AuctionLots','v35TradeShock','v35TradeShockUntil','v35EconomyEvents'])delete s.world[k]}
const {api}=fresh();for(const fn of ['v35EconomySnapshot','v35ShopRegistry','v35ListingRegistry','v35ShopAccess','v35ListingAccess','v35Quote','v35Trade','v35ApplyWarShock','v35NpcNamedMaterialSpec','v35SecretRealmTradeReward','v35EconomyHealthSnapshot','v35SetPlayerForTest','v34CatalogSnapshot','v33CatalogSnapshot','v32CatalogSnapshot','v31CatalogSnapshot'])assert.equal(typeof api[fn],'function',fn);
let s=api.getState();assert.equal(s.version,'3.5.0');assert.equal(s.saveSchemaVersion,32);assert.equal(s.player.contentStateVersion,6);assert.equal(s.player.v35EconomyVersion,1);
let snap=api.v35EconomySnapshot();assert.equal(snap.shops,4);assert.equal(snap.fixedListings,32);assert.equal(snap.auctionPool,12);assert.equal(snap.auctionLots,5);assert.equal(snap.health.multiSource,true);
const reg=api.contentRegistrySnapshot();assert.equal(reg.registryVersion,6);assert.equal(reg.counts.shops,4);assert.equal(reg.counts.materials,48);assert.equal(reg.counts.recipes,24);assert.equal(reg.counts.enemies,48);
// schema31 -> 32 preserves V3.4 and V3.3 state.
const old=api.getState();old.version='3.4.0';old.saveSchemaVersion=31;old.player.contentStateVersion=5;old.player.v34BuildWins['build-sword-burst']=3;old.player.materialInventoryById['mat-v33-greenleaf']=7;stripV35(old);const od=loadState(old),oa=od.window.__TAIXUAN_TEST__,os=oa.getState();assert.equal(os.version,'3.5.0');assert.equal(os.saveSchemaVersion,32);assert.equal(os.player.v34BuildWins['build-sword-burst'],3);assert.equal(os.player.materialInventoryById['mat-v33-greenleaf'],7);assert.equal(os.player.v35EconomyVersion,1);
// Public market named-material buy/sell is atomic and stock-limited.
oa.v35SetPlayerForTest({realmIndex:15,location:'临江城',stones:1000,standing:{xuanshui:0}});let before=oa.getState(),q=oa.v35Quote('listing-market-greenleaf','buy',1),r=oa.v35Trade('listing-market-greenleaf','buy',1);assert.equal(r.ok,true);let after=oa.getState();assert.equal(after.player.spiritStones,before.player.spiritStones-q.total);assert.equal(after.player.materialInventoryById['mat-v33-greenleaf'],before.player.materialInventoryById['mat-v33-greenleaf']+1);assert.equal(r.stock,11);let sell=oa.v35Trade('listing-market-greenleaf','sell',1);assert.equal(sell.ok,true);after=oa.getState();assert(after.player.v35NamedTrades>=2);assert(after.player.v35TradeLedger.length>=2);
// Failed purchase changes neither money, item nor stock.
oa.v35SetPlayerForTest({location:'临江城',stones:0});before=oa.getState();const stock0=oa.v35ListingRegistry()['listing-market-ginseng'];const fail=oa.v35Trade('listing-market-ginseng','buy',1);assert.equal(fail.ok,false);assert.equal(fail.reason,'currency');after=oa.getState();assert.equal(after.player.spiritStones,0);assert.equal(after.player.materialInventoryById['mat-v33-ginseng-root'],before.player.materialInventoryById['mat-v33-ginseng-root']);assert.equal(oa.v35ListingRegistry()['listing-market-ginseng'].stock,stock0.stock);
// Sect vault spends contribution and enforces sect access.
oa.v35SetPlayerForTest({realmIndex:16,location:'青云山',sect:'散修',sectRank:'无',contribution:500});assert.equal(oa.v35ShopAccess('shop-qingyun-vault').ok,false);oa.v35SetPlayerForTest({sect:'青云宗',sectRank:'真传弟子',contribution:500});const c0=oa.getState().player.sectContribution;const sectTrade=oa.v35Trade('listing-sect-recipe-swordheart','buy',1);assert.equal(sectTrade.ok,true);after=oa.getState();assert(after.player.sectContribution<c0);assert(after.player.knownRecipeIds.includes('recipe-v33-swordheart'));
// Black-market faction standing changes prices.
oa.v35SetPlayerForTest({realmIndex:20,location:'黑风岭',sect:'散修',standing:{blood:-60},stones:5000});const hostile=oa.v35Quote('listing-black-souljade','buy',1).unit;oa.v35SetPlayerForTest({standing:{blood:60}});const friendly=oa.v35Quote('listing-black-souljade','buy',1).unit;assert(friendly<hostile,'blood standing should discount black market');
// War shortage makes public market dearer and black market relatively looser.
oa.v35SetPlayerForTest({location:'临江城',standing:{xuanshui:0,blood:0}});oa.getState().world;oa.v35ApplyWarShock('relief');const relief=oa.v35Quote('listing-market-greenleaf','buy',1).unit;oa.v35ApplyWarShock('shortage');const shortage=oa.v35Quote('listing-market-greenleaf','buy',1).unit;assert(shortage>relief,'shortage should raise public market price');
// Auction has five deterministic limited lots; purchase decrements one lot.
oa.v35SetPlayerForTest({realmIndex:25,location:'苍梧郡城',stones:10000});const lots=Object.values(oa.v35ListingRegistry()).filter(x=>x.shopId==='shop-cangwu-auction');assert.equal(lots.length,5);const lot=lots.find(x=>oa.v35ListingAccess(x).ok);assert(lot,'no accessible auction lot');const lotStock=lot.stock;const auc=oa.v35Trade(lot.id,'buy',1);assert.equal(auc.ok,true);assert.equal(auc.stock,lotStock-1);assert(oa.getState().player.v35AuctionWins>=1);
// Named-material NPC request consumes the exact requested stable materialId.
const ns=oa.getState();const candidate=ns.npcs.map(n=>({n,spec:oa.v35NpcNamedMaterialSpec(n)})).find(x=>x.spec);assert(candidate,'no NPC has named-material request candidate');oa.v33AddMaterial(candidate.spec.materialId,2);const namedBefore=oa.getState().player.materialInventoryById[candidate.spec.materialId];oa.forceNpcHelpRequestById(candidate.n.id,'namedMaterial');const req=oa.getState().world.npcPendingRequest;assert.equal(req.type,'namedMaterial');assert(req.materialId);assert.equal(oa.resolveNpcHelpRequestForTest('help'),'helped');assert.equal(oa.getState().player.materialInventoryById[req.materialId],namedBefore-1);
// Secret realm economic reward adds regional material and can unlock an unknown recipe.
oa.v35SetPlayerForTest({realmIndex:23,location:'古河遗迹'});const known0=oa.getState().player.knownRecipeIds.length;const sr=oa.v35SecretRealmTradeReward({location:'古河遗迹',threat:8});assert(sr.materialId,'secret realm regional material missing');assert(sr.recipeId,'secret realm recipe missing');assert.equal(oa.getState().player.knownRecipeIds.length,known0+1);assert(oa.getState().player.v35SecretRealmRecipes>=1);
// Previous systems remain intact.
assert.equal(oa.v34CatalogSnapshot().enemies,48);assert.equal(oa.v34CatalogSnapshot().builds,8);assert.equal(oa.v33CatalogSnapshot().materials,48);assert.equal(oa.v33CatalogSnapshot().recipes,24);assert.equal(oa.v32CatalogSnapshot().equipment,60);assert.equal(oa.v31CatalogSnapshot().manuals.length,28);
// Save/reload keeps economy state.
const saved=oa.getState(),rd=loadState(saved),ra=rd.window.__TAIXUAN_TEST__,rs=ra.getState();assert.equal(rs.saveSchemaVersion,32);assert(rs.player.v35TradeLedger.length>=saved.player.v35TradeLedger.length);assert.equal(rs.world.v35TradeShock,'shortage');
// Future schema33 must never be overwritten.
const future=ra.getState();future.saveSchemaVersion=33;future.version='future-v35';const futureRaw=JSON.stringify(future),fd=makeDom(futureRaw);fd.window.document.getElementById('continueBtn').click();assert.equal(fd.window.localStorage.getItem(SAVE_KEY),futureRaw);assert.equal(fd.window.__TAIXUAN_TEST__.getState(),null);
console.log('V35_REGRESSION_PASS',JSON.stringify({version:'3.5.0',schema:32,shops:4,fixedListings:32,auctionPool:12,auctionLots:5,namedTrade:true,atomicTrade:true,sectContribution:true,blackMarketStanding:true,warShock:true,auctionLimited:true,npcNamedRequest:true,secretRealmRecipe:true,multiSourceHighTier:true,v34Preserved:true,v33Preserved:true,futureSaveProtected:true}));
