import fs from 'fs';import assert from 'assert';import {JSDOM} from 'jsdom';
const INDEX_PATH=process.env.INDEX_PATH||'index.html',GAME_PATH=process.env.GAME_PATH||'src/game-v37.js',SAVE_KEY='xiuxian_world_v02';const htmlRaw=fs.readFileSync(INDEX_PATH,'utf8'),source=fs.readFileSync(GAME_PATH,'utf8');assert(source.includes("const VERSION='3.7.0'"));assert(source.includes('const SAVE_SCHEMA_VERSION=34'));for(const x of ['v37ChooseLaw','v37IntegrateUnity','v37ActivateDomain','v37ActivateAvatar','v37StartHighWar','合体初期'])assert(source.includes(x),x);
function cleanHtml(h){return h.replace(/<script[^>]+src=["'][^"']*app\.js[^"']*["'][^>]*><\/script>/i,'')}function makeDom(seed=null){const d=new JSDOM(cleanHtml(htmlRaw),{url:'http://example.test/',runScripts:'outside-only',pretendToBeVisual:true});d.window.matchMedia=()=>({matches:false,addListener(){},removeListener(){}});d.window.scrollTo=()=>{};d.window.console=console;if(seed!==null)d.window.localStorage.setItem(SAVE_KEY,seed);d.window.eval(source);return d}function fresh(){const d=makeDom(),api=d.window.__TAIXUAN_TEST__;api.newGame('V37回归');return {d,api}}function loadState(o){const d=makeDom(JSON.stringify(o));d.window.document.getElementById('continueBtn').click();return d}function stripV37(s){for(const k of ['v37UnityVersion','v37LawId','v37LawProficiency','v37Unity','v37LawBacklash','v37UnityFailures','v37LawActions','v37DomainUses','v37AvatarUses','v37HighWarWins','unityEssence'])delete s.player[k];for(const k of ['v37WarCycle','v37WarStatus','v37WarScore','v37EnemyScore','v37WarUntil','v37WarEvents','v37LastWarResult'])delete s.world[k]}
let {api}=fresh();for(const fn of ['v37LawRegistry','v37ChooseLaw','v37ContemplateLaw','v37IntegrateUnity','v37CraftUnityEssence','v37AttemptUnityBreakthrough','v37MinorGate','v37ActivateDomain','v37ActivateAvatar','v37WarSnapshot','v37StartHighWar','v37JoinWarFront','v37CatalogSnapshot','v37StateSnapshot','v37SetPlayerForTest','v36StateSnapshot','v35EconomySnapshot'])assert.equal(typeof api[fn],'function',fn);
let s=api.getState();assert.equal(s.version,'3.7.0');assert.equal(s.saveSchemaVersion,34);assert.equal(s.player.contentStateVersion,8);let cat=api.v37CatalogSnapshot();assert.deepEqual({realms:cat.realms,regions:cat.regions,routes:cat.routes,materials:cat.materials,recipes:cat.recipes,manuals:cat.manuals,spells:cat.spells,equipment:cat.equipment,artifacts:cat.artifacts,enemies:cat.enemies,laws:cat.laws,warFronts:cat.warFronts},{realms:34,regions:20,routes:32,materials:72,recipes:40,manuals:36,spells:84,equipment:76,artifacts:40,enemies:72,laws:4,warFronts:3});const reg=api.contentRegistrySnapshot();assert.equal(reg.registryVersion,8);assert.equal(reg.counts.laws,4);assert.equal(reg.counts.realms,34);assert.equal(Object.keys(reg.laws).length,4);
// schema33 -> 34 preserves V3.6 spatial state and V3.5 economy.
let old=api.getState();old.version='3.6.0';old.saveSchemaVersion=33;old.player.contentStateVersion=7;old.player.v36SpaceInsight=47;old.player.v35NamedTrades=9;stripV37(old);let od=loadState(old),oa=od.window.__TAIXUAN_TEST__,os=oa.getState();assert.equal(os.version,'3.7.0');assert.equal(os.saveSchemaVersion,34);assert.equal(os.player.v36SpaceInsight,47);assert.equal(os.player.v35NamedTrades,9);assert.equal(os.player.v37LawProficiency,0);assert.equal(os.player.v37Unity,0);
// Law tendency is explicit and fixed; contemplation and threefold unity are independent progression axes.
oa.v37SetPlayerForTest({realmIndex:29,location:'法则古原',spaceInsight:60,insight:50});let choose=oa.v37ChooseLaw('law-severing',true);assert.equal(choose.ok,true);assert.equal(oa.v37StateSnapshot().lawId,'law-severing');assert.equal(oa.v37ChooseLaw('law-annihilation',true).reason,'fixed');let law=oa.v37ContemplateLaw(40);assert.equal(law.ok,true);assert(oa.v37StateSnapshot().lawProficiency>=45);oa.v37SetPlayerForTest({location:'万象法坛'});let unity=oa.v37IntegrateUnity(40);assert.equal(unity.ok,true);assert.equal(oa.v37StateSnapshot().unity,40);
// Unity essence and dedicated major breakthrough are mandatory.
oa.v37SetPlayerForTest({location:'归一圣墟'});for(let i=0;i<4;i++)assert.equal(oa.v37CraftUnityEssence(true).ok,true);oa.v37SetPlayerForTest({realmIndex:29,lawProficiency:45,unity:40,unityEssence:4,insight:40,progressFull:true});let br=oa.v37AttemptUnityBreakthrough('success');assert.equal(br.outcome,'success');s=oa.getState();assert.equal(s.player.realmIndex,30);assert(s.player.lifespan>=8000);assert.equal(s.player.v37LawId,'law-severing');
// Major failure has real root/lifespan cost.
oa.newGame('V37失败回归');oa.v37SetPlayerForTest({realmIndex:29,location:'归一圣墟',lawId:'law-immovable',lawProficiency:50,unity:50,unityEssence:4,insight:40,spaceInsight:60,progressFull:true});let life0=oa.getState().player.lifespan;let fail=oa.v37AttemptUnityBreakthrough('fail');assert.equal(fail.outcome,'failure');s=oa.getState();assert.equal(s.player.realmIndex,29);assert.equal(s.player.injury,3);assert.equal(s.player.v37LawProficiency,45);assert.equal(s.player.v37Unity,42);assert(s.player.lifespan<life0);assert(s.player.v37UnityFailures>=1);
// Minor unity realms require law proficiency AND unity, not experience alone.
oa.v37SetPlayerForTest({realmIndex:30,lawProficiency:59,unity:55});assert.equal(oa.v37MinorGate(30).ok,false);oa.v37SetPlayerForTest({lawProficiency:60,unity:55});assert.equal(oa.v37MinorGate(30).ok,true);
// Domain and avatar become real combat states.
oa.v37SetPlayerForTest({realmIndex:31,lawId:'law-immovable',lawProficiency:100,unity:70});oa.startCombat('法纹裂狼');assert.equal(oa.v37ActivateDomain(true),true);assert.equal(oa.v37ActivateAvatar(true),true);let c=oa.getCombat();assert(c.v37DomainTurns>=4);assert(c.v37AvatarTurns>=3);const hp0=c.enemyHp;oa.combatAction('attack');c=oa.getCombat();assert(c===null||c.enemyHp<hp0);if(c){assert(c.v37DomainTurns<4);assert(c.v37AvatarTurns<3)}
// High-tier war is regional, front-based and resolves from accumulated victories exactly once per front.
oa.newGame('V37战争回归');oa.v37SetPlayerForTest({realmIndex:31,location:'天衡战城',lawId:'law-severing',lawProficiency:100,unity:70});oa.v37StartHighWar(true);for(const f of ['front-lawplain','front-tianheng','front-altar'])assert.equal(oa.v37JoinWarFront(f,'win').ok,true);let war=oa.v37WarSnapshot();assert.equal(war.score,3);assert.equal(war.lastResult,'victory');assert.equal(war.status,'peace');assert.equal(oa.v37StateSnapshot().warWins,3);
// V3.6 space and V3.5 economy remain live.
let v36=oa.v36StateSnapshot();assert('spaceInsight'in v36);let eco=oa.v35EconomySnapshot();assert.equal(eco.shops,4);assert.equal(oa.v37CatalogSnapshot().warFronts,3);
// Save/reload preserves law, unity and war result.
const saved=oa.getState(),rd=loadState(saved),ra=rd.window.__TAIXUAN_TEST__,rs=ra.getState();assert.equal(rs.saveSchemaVersion,34);assert.equal(rs.player.v37LawId,'law-severing');assert.equal(rs.world.v37LastWarResult,'victory');
// future schema35 is protected.
const future=ra.getState();future.saveSchemaVersion=35;future.version='future-v37';const raw=JSON.stringify(future),fd=makeDom(raw);fd.window.document.getElementById('continueBtn').click();assert.equal(fd.window.localStorage.getItem(SAVE_KEY),raw);assert.equal(fd.window.__TAIXUAN_TEST__.getState(),null);
console.log('V37_REGRESSION_PASS',JSON.stringify({version:'3.7.0',schema:34,realms:34,laws:4,lawProficiency:true,unity:true,unityEssence:true,domain:true,avatar:true,highWar:true,warWinCountExact:true,majorFailure:true,v36Preserved:true,v35Preserved:true,futureSaveProtected:true}));
