import fs from 'fs';
import assert from 'assert';
import {JSDOM} from 'jsdom';
const INDEX_PATH=process.env.INDEX_PATH||'index.html',GAME_PATH=process.env.GAME_PATH||'src/game-v39.js',SAVE_KEY='xiuxian_world_v02';
const htmlRaw=fs.readFileSync(INDEX_PATH,'utf8'),source=fs.readFileSync(GAME_PATH,'utf8');
assert(source.includes("const VERSION='3.9.0'"));assert(source.includes('const SAVE_SCHEMA_VERSION=36'));assert(source.includes('const CONTENT_STATE_VERSION=10'));
for(const x of ['渡劫境','真仙','v39BeginTribulation','v39ResolveThunder','v39ResolveHeartDemon','v39ResolveTransformation','v39AscendToTrueImmortal','v39BuildTribulationFormation'])assert(source.includes(x),x);
function cleanHtml(h){return h.replace(/<script[^>]+src=["'][^"']*app\.js[^"']*["'][^>]*><\/script>/i,'')}
function makeDom(seed=null){const d=new JSDOM(cleanHtml(htmlRaw),{url:'http://example.test/',runScripts:'outside-only',pretendToBeVisual:true});d.window.matchMedia=()=>({matches:false,addListener(){},removeListener(){}});d.window.scrollTo=()=>{};d.window.console=console;if(seed!==null)d.window.localStorage.setItem(SAVE_KEY,seed);d.window.eval(source);return d}
function fresh(){const d=makeDom(),api=d.window.__TAIXUAN_TEST__;api.newGame('V39回归');return {d,api}}
function loadState(o){const d=makeDom(JSON.stringify(o));d.window.document.getElementById('continueBtn').click();return d}
function stripV39(s){for(const k of ['v39FinaleVersion','v39TribulationStatus','v39TribulationAttempt','v39ThunderStage','v39TribulationFailures','v39HeartDemonFailures','v39TransformationStep','v39FormationId','v39FormationIntegrity','v39PillGuards','v39LastFailureStage','v39TribulationHistory','v39AscensionComplete','v39TrueImmortalArchive','tribulationEssence'])delete s.player[k];for(const k of ['v39AscensionCount','v39LastAscender','v39HeavenGateOpen'])delete s.world[k];if(s.legacy)delete s.legacy.trueImmortalArchives}
function makeNatal(api,itemId='item-v37-lawcleaver-sword',marks=7){assert.equal(api.forgeV32Item(itemId,true,'perfect'),'perfect');assert.equal(api.bindV32Artifact(itemId,true),'ok');for(let i=0;i<3;i++)assert.equal(api.refineV32Artifact(itemId,'success'),'success');for(let i=0;i<2;i++)assert.equal(api.warmV32Artifact(itemId,true),10);assert.equal(api.makeNatalV32Artifact(itemId,true),'ok');for(let i=0;i<marks;i++)assert.equal(api.v38TemperNatalOrigin(true).ok,true);return itemId}
function equipTribulationGuard(api){const id='item-v39-thunder-umbrella';assert.equal(api.forgeV32Item(id,true,'perfect'),'perfect');assert.equal(api.bindV32Artifact(id,true),'ok');assert(api.equipV32Artifact(id));return id}
let {api}=fresh();
for(const fn of ['ensureV39FinaleShape','syncV39FinaleState','v39FormationRegistry','v39BuildTribulationFormation','v39ArmTribulationPill','v39TribulationReadiness','v39BeginTribulation','v39ThunderStage','v39ResolveThunder','v39ResolveHeartDemon','v39ResolveTransformation','v39AscendToTrueImmortal','v39TravelGate','v39EnemyMechanic','v39CatalogSnapshot','v39StateSnapshot','v39SetPlayerForTest','v39FinaleText','v38StateSnapshot','forgeV32Item','bindV32Artifact','equipV32Artifact','makeNatalV32Artifact'])assert.equal(typeof api[fn],'function',fn);
let s=api.getState();assert.equal(s.version,'3.9.0');assert.equal(s.saveSchemaVersion,36);assert.equal(s.player.contentStateVersion,10);let cat=api.v39CatalogSnapshot();assert.deepEqual({realms:cat.realms,regions:cat.regions,routes:cat.routes,materials:cat.materials,recipes:cat.recipes,manuals:cat.manuals,spells:cat.spells,equipment:cat.equipment,artifacts:cat.artifacts,enemies:cat.enemies,auctionPool:cat.auctionPool,formations:cat.formations,thunderStages:cat.thunderStages,transformationStages:cat.transformationStages},{realms:40,regions:27,routes:41,materials:94,recipes:54,manuals:44,spells:108,equipment:92,artifacts:56,enemies:94,auctionPool:24,formations:4,thunderStages:6,transformationStages:3});
const reg=api.contentRegistrySnapshot();assert.equal(reg.registryVersion,10);assert.equal(reg.counts.formations,4);assert.equal(Object.keys(reg.formations).length,4);

// schema35 -> 36 preserves the finished V3.8 state and initializes only V3.9 finale state.
let old=api.getState();old.version='3.8.0';old.saveSchemaVersion=35;old.player.contentStateVersion=9;old.player.realmIndex=37;old.player.v38OriginInsight=311;old.player.v38WorldAuthority=176;old.player.v38NatalOriginMarks=7;old.player.v38TribulationPrep={body:72,soul:73,law:74,artifact:75,formation:76};old.world.v38WorldOrder=68;stripV39(old);let od=loadState(old),oa=od.window.__TAIXUAN_TEST__,os=oa.getState();assert.equal(os.version,'3.9.0');assert.equal(os.saveSchemaVersion,36);assert.equal(os.player.v38OriginInsight,311);assert.equal(os.player.v38WorldAuthority,176);assert.equal(os.player.v38NatalOriginMarks,7);assert.deepEqual(os.player.v38TribulationPrep,{body:72,soul:73,law:74,artifact:75,formation:76});assert.equal(os.world.v38WorldOrder,68);assert.equal(os.player.v39TribulationStatus,'idle');

// Real V3.2/V3.7 natal lifecycle + a real anti-tribulation artifact must satisfy the V3.9 readiness gate.
oa.newGame('V39终局成功');makeNatal(oa,'item-v37-lawcleaver-sword',7);equipTribulationGuard(oa);oa.v39SetPlayerForTest({realmIndex:37,location:'九霄劫台',progressFull:true,injury:0,originInsight:320,authority:180,natalMarks:7,lawProficiency:240,unity:150,prep:{body:80,soul:80,law:80,artifact:80,formation:80}});assert.equal(oa.v39BuildTribulationFormation('formation-v39-nine-heavens',true).ok,true);let ready=oa.v39TribulationReadiness();assert.equal(ready.ready,true,JSON.stringify(ready));assert(ready.artifactScore>=.10);assert.equal(ready.formationId,'formation-v39-nine-heavens');

// Six thunder stages are sequential and cannot be skipped; all pass moves into the heart-demon stage.
let begin=oa.v39BeginTribulation();assert.equal(begin.ok,true);assert.equal(oa.v39StateSnapshot().status,'thunder');for(let i=0;i<6;i++){const stage=oa.v39ThunderStage();assert(stage);const r=oa.v39ResolveThunder('balanced','success');assert.equal(r.outcome,'success')}assert.equal(oa.v39StateSnapshot().status,'heart');assert.equal(oa.v39StateSnapshot().thunderStage,6);
let heart=oa.v39ResolveHeartDemon('self','success');assert.equal(heart.outcome,'success');assert.equal(oa.v39StateSnapshot().status,'transformation');
for(let i=0;i<3;i++){const r=oa.v39ResolveTransformation('balanced','success');assert.equal(r.outcome,'success')}s=oa.getState();assert.equal(s.player.realmIndex,38);assert.equal(s.player.v39TribulationStatus,'ascension');assert.equal(s.world.v39HeavenGateOpen,true);assert.equal(s.flags.gameCompleted||false,false);
let asc=oa.v39AscendToTrueImmortal(true);assert.equal(asc.outcome,'true-immortal');s=oa.getState();assert.equal(s.player.realmIndex,39);assert.equal(s.player.v39TribulationStatus,'complete');assert.equal(s.player.v39AscensionComplete,true);assert.equal(s.flags.gameCompleted,true);assert.equal(s.flags.trueImmortalEnding,true);assert.equal(s.player.v39TrueImmortalArchive.ending,'真仙飞升');assert(s.legacy.trueImmortalArchives.length>=1);assert(s.player.lifespan>=1000000);

// A normal failure is heavy and returns to the tribulation terrace instead of silently succeeding.
oa.newGame('V39失败');oa.v39SetPlayerForTest({realmIndex:37,location:'九霄劫台',progressFull:true,injury:0,originInsight:320,authority:180,natalMarks:7,lawProficiency:240,unity:150,prep:{body:80,soul:80,law:80,artifact:80,formation:80}});let life0=oa.getState().player.lifespan;assert.equal(oa.v39BeginTribulation(true).ok,true);let fail=oa.v39ResolveThunder('balanced','fail');assert.equal(fail.outcome,'failure');s=oa.getState();assert.equal(s.player.realmIndex,37);assert.equal(s.player.injury,3);assert.equal(s.player.location,'九霄劫台');assert.equal(s.player.v39TribulationStatus,'failed');assert(s.player.lifespan<life0);

// Late thunder can be genuinely fatal; this is not a display-only warning.
oa.newGame('V39致命');oa.v39SetPlayerForTest({realmIndex:37,location:'九霄劫台',progressFull:true,injury:0,originInsight:320,authority:180,natalMarks:7,lawProficiency:240,unity:150,prep:{body:90,soul:90,law:90,artifact:90,formation:90}});assert.equal(oa.v39BeginTribulation(true).ok,true);for(let i=0;i<4;i++)assert.equal(oa.v39ResolveThunder('balanced','success').outcome,'success');let fatal=oa.v39ResolveThunder('balanced','fatal');assert.equal(fatal.outcome,'fatal');s=oa.getState();assert.equal(s.flags.dead,true);assert.equal(s.flags.deathCause,'渡仙劫失败');

// V3.9 enemy mechanics are in the existing combat engine, not a second combat system.
oa.newGame('V39战斗');oa.v39SetPlayerForTest({realmIndex:38,location:'仙凡界隙',originInsight:320,authority:180,prep:{body:80,soul:80,law:80,artifact:80,formation:80}});oa.startCombat('仙凡裂影');let cb=oa.getCombat();assert(cb&&cb.enemy.name==='仙凡裂影');const hp0=cb.enemyHp;oa.combatAction('attack');cb=oa.getCombat();assert(cb===null||cb.enemyHp<hp0);

// Save/reload keeps terminal progress and future schema37 is never overwritten by V3.9.
oa.newGame('V39存档');oa.v39SetPlayerForTest({realmIndex:37,location:'九霄劫台',originInsight:310,authority:175,prep:{body:61,soul:62,law:63,artifact:64,formation:65}});assert.equal(oa.v39BuildTribulationFormation('formation-v39-five-elements',true).ok,true);const saved=oa.getState(),rd=loadState(saved),ra=rd.window.__TAIXUAN_TEST__,rs=ra.getState();assert.equal(rs.saveSchemaVersion,36);assert.equal(rs.player.v39FormationId,'formation-v39-five-elements');assert.equal(rs.player.v38OriginInsight,310);assert.equal(rs.player.v38WorldAuthority,175);const future=ra.getState();future.saveSchemaVersion=37;future.version='future-v39';const raw=JSON.stringify(future),fd=makeDom(raw);fd.window.document.getElementById('continueBtn').click();assert.equal(fd.window.localStorage.getItem(SAVE_KEY),raw);assert.equal(fd.window.__TAIXUAN_TEST__.getState(),null);
console.log('V39_REGRESSION_PASS',JSON.stringify({version:'3.9.0',schema:36,realms:40,formations:4,sixThunder:true,heartDemon:true,threeTransformations:true,realFailure:true,fatalTribulation:true,trueImmortalEnding:true,archive:true,v38Preserved:true,existingCombatIntegrated:true,futureSaveProtected:true}));