import fs from 'fs';
import assert from 'assert';
import {JSDOM} from 'jsdom';
const INDEX_PATH=process.env.INDEX_PATH||'index.html';const GAME_PATH=process.env.GAME_PATH||'src/game-v36.js';
const htmlRaw=fs.readFileSync(INDEX_PATH,'utf8'),source=fs.readFileSync(GAME_PATH,'utf8'),SAVE_KEY='xiuxian_world_v02';
assert(source.includes("const VERSION='3.6.0'"));assert(source.includes('const SAVE_SCHEMA_VERSION=33'));for(const x of ['炼虚初期','上古断界台','mat-v36-void-essence','v36ContemplateSpace','v36AttemptRefiningBreakthrough','renderV36VoidPanel'])assert(source.includes(x),x);
function cleanHtml(h){return h.replace(/<script[^>]+src=["'][^"']*app\.js[^"']*["'][^>]*><\/script>/i,'')}
function makeDom(seed=null){const d=new JSDOM(cleanHtml(htmlRaw),{url:'http://example.test/',runScripts:'outside-only',pretendToBeVisual:true});d.window.matchMedia=()=>({matches:false,addListener(){},removeListener(){}});d.window.scrollTo=()=>{};d.window.console=console;if(seed!==null)d.window.localStorage.setItem(SAVE_KEY,seed);d.window.eval(source);return d}
function fresh(name='V36回归'){const d=makeDom(),api=d.window.__TAIXUAN_TEST__;api.newGame(name);return {d,api}}
function loadState(o){const d=makeDom(JSON.stringify(o));d.window.document.getElementById('continueBtn').click();return d}
function stripV36(s){for(const k of ['v36VoidVersion','v36SpaceInsight','v36VoidBacklash','v36RefiningFailures','v36SpaceActions','v36SpaceSkillUses','v36RiftWins','voidEssence'])delete s.player[k];for(const k of ['v36VoidEvents','v36LastVoidEventDay'])delete s.world[k];if(s.player.materialInventoryById)delete s.player.materialInventoryById['mat-v36-void-essence'];if(s.player.materialCountsById)delete s.player.materialCountsById['mat-v36-void-essence']}
const {api}=fresh();for(const fn of ['v36CatalogSnapshot','v36StateSnapshot','v36SetPlayerForTest','v36TravelGate','v36ContemplateSpace','v36CraftVoidEssence','v36AttemptRefiningBreakthrough','v36MajorReady','v36BreakthroughBonus','v36SpaceDamageMultiplier','v36AfterSpaceSkill','v36IncomingMultiplier','v36EnemySpaceLocked','v35EconomySnapshot','v34CatalogSnapshot','v33CatalogSnapshot','v32CatalogSnapshot','v31CatalogSnapshot'])assert.equal(typeof api[fn],'function',fn);
let s=api.getState();assert.equal(s.version,'3.6.0');assert.equal(s.saveSchemaVersion,33);assert.equal(s.player.contentStateVersion,7);assert.equal(s.player.v36VoidVersion,1);assert.equal(s.player.v36SpaceInsight,0);
const c=api.v36CatalogSnapshot();assert.deepEqual({realms:c.realms,regions:c.regions,routes:c.routes,materials:c.materials,recipes:c.recipes,manuals:c.manuals,spells:c.spells,equipment:c.equipment,artifacts:c.artifacts,enemies:c.enemies,auctionPool:c.auctionPool},{realms:30,regions:16,routes:26,materials:60,recipes:32,manuals:32,spells:72,equipment:68,artifacts:32,enemies:60,auctionPool:16});
const reg=api.contentRegistrySnapshot();assert.equal(reg.registryVersion,7);assert.equal(reg.counts.realms,30);assert.equal(reg.counts.regions,16);assert.equal(reg.counts.materials,60);assert.equal(reg.counts.recipes,32);assert.equal(reg.counts.enemies,60);assert.equal(reg.counts.shops,4);for(const id of ['realm-refining-early','realm-refining-perfect'])assert(reg.realms[id],id);for(const id of ['region-tianyuan-city','region-ancient-boundary-platform'])assert(reg.regions[id],id);for(const id of ['mat-v36-space-crystal','mat-v36-void-essence'])assert(reg.materials[id],id);
// schema32 -> 33 preserves V3.5 economy and initializes refining-void state.
const old=api.getState();old.version='3.5.0';old.saveSchemaVersion=32;old.player.contentStateVersion=6;old.player.v35NamedTrades=9;old.player.v34BuildWins['build-sword-burst']=4;stripV36(old);const od=loadState(old),oa=od.window.__TAIXUAN_TEST__,os=oa.getState();assert.equal(os.version,'3.6.0');assert.equal(os.saveSchemaVersion,33);assert.equal(os.player.v35NamedTrades,9);assert.equal(os.player.v34BuildWins['build-sword-burst'],4);assert.equal(os.player.v36VoidVersion,1);assert.equal(os.player.v36SpaceInsight,0);
// High-region routes have both realm and space-insight gates.
oa.v36SetPlayerForTest({realmIndex:24,location:'天渊城',spaceInsight:0});let route=oa.routeInfo('天渊城','空冥裂谷')[0];assert(route);let gate=oa.v36TravelGate(route,'空冥裂谷');assert.equal(gate.ok,false);assert.equal(gate.reason,'realm');oa.v36SetPlayerForTest({realmIndex:25,spaceInsight:0});gate=oa.v36TravelGate(route,'空冥裂谷');assert.equal(gate.ok,false);assert.equal(gate.reason,'space');oa.v36SetPlayerForTest({spaceInsight:4});assert.equal(oa.v36TravelGate(route,'空冥裂谷').ok,true);
// Space contemplation is a real progression axis, not a label.
oa.v36SetPlayerForTest({realmIndex:26,location:'空冥裂谷',spaceInsight:4});const si0=oa.v36StateSnapshot().spaceInsight,con=oa.v36ContemplateSpace(true);assert.equal(con.ok,true);assert(con.gain>=2);assert(oa.v36StateSnapshot().spaceInsight>si0);assert(oa.v36StateSnapshot().spaceActions>=1);
// Refining essence is a stable named breakthrough material.
const e0=oa.v36StateSnapshot().voidEssence;const ess=oa.v36CraftVoidEssence(true);assert.equal(ess.ok,true);assert.equal(oa.v36StateSnapshot().voidEssence,e0+1);assert.equal(oa.getState().player.materialInventoryById['mat-v36-void-essence'],e0+1);
// Dedicated 化神后期 -> 炼虚初期 breakthrough consumes high-tier requirements and raises lifespan floor.
const {api:sa}=fresh('V36成功');sa.v36SetPlayerForTest({realmIndex:25,location:'虚空裂隙',spaceInsight:25,voidEssence:5,insight:30,deification:8,injury:0,progressFull:true});const beforeSuccess=sa.getState();const suc=sa.v36AttemptRefiningBreakthrough('success');assert.equal(suc.ok,true);assert.equal(suc.outcome,'success');const ss=sa.getState();assert.equal(ss.player.realmIndex,26);assert.equal(ss.player.v36SpaceInsight,25);assert.equal(ss.player.voidEssence,0);assert.equal(ss.player.deificationEssence,beforeSuccess.player.deificationEssence-3);assert.equal(ss.player.insight,beforeSuccess.player.insight-18);assert(ss.player.lifespan>=3500);
// Refining failure has qualitatively harsher void backlash, lifespan loss and space-insight loss.
const {api:fa}=fresh('V36失败');fa.v36SetPlayerForTest({realmIndex:25,location:'虚空裂隙',spaceInsight:25,voidEssence:5,insight:30,deification:8,injury:0,progressFull:true});const fl0=fa.getState().player.lifespan;const fail=fa.v36AttemptRefiningBreakthrough('fail');assert.equal(fail.ok,true);assert.equal(fail.outcome,'failure');const fs0=fa.getState();assert.equal(fs0.player.realmIndex,25);assert.equal(fs0.player.injury,3);assert.equal(fs0.player.v36RefiningFailures,1);assert.equal(fs0.player.v36VoidBacklash,1);assert.equal(fs0.player.v36SpaceInsight,22);assert(fs0.player.lifespan<fl0);assert(fs0.player.progress<2300000);
// New manuals/spells use the existing V3.1 acquisition/loadout system.
sa.v36SetPlayerForTest({realmIndex:29,location:'上古断界台',spaceInsight:40});assert.equal(sa.learnV31Manual('manual-v36-heavenvoid-sword',true),'learned');assert.equal(sa.learnV31Spell('spell-v36-spirit-phase',true),'learned');assert(sa.getState().player.manualLibraryIds.includes('manual-v36-heavenvoid-sword'));assert('太虚化空' in sa.getState().player.spells);
// Space skill semantics: shift, lock and phase are actual combat state, and space-rend scales damage.
assert(sa.v36SpaceDamageMultiplier({spaceRend:.2})>1);sa.startCombat('断界台残灵');sa.equipV31Skill(0,'spell-v36-spirit-phase');let enemy=sa.getCombat().enemy;assert.equal(sa.useV31CombatSkill('spell-v36-spirit-phase',enemy),true);assert(sa.getCombat().v36VoidPhase>=2);const incoming=sa.v36IncomingMultiplier();assert(incoming<.5);assert.equal(sa.getCombat().v36VoidPhase,1);assert.equal(sa.learnV31Spell('spell-v36-spirit-lock',true),'learned');sa.equipV31Skill(1,'spell-v36-spirit-lock');enemy=sa.getCombat().enemy;assert.equal(sa.useV31CombatSkill('spell-v36-spirit-lock',enemy),true);assert.equal(sa.v36EnemySpaceLocked(),true);
// New high-tier enemies expose stable IDs and inline independent mechanics.
for(const id of ['enemy-v36-kongming-mantis','enemy-v36-boundary-warden','enemy-v36-boundary-lord']){assert(reg.enemies[id],id);assert(reg.enemies[id].mechanicId,id+' mechanic')}
// V3.5 and earlier systems remain intact; auction now gains limited V3.6 high-tier entries.
const eco=sa.v35EconomySnapshot();assert.equal(eco.shops,4);assert.equal(eco.fixedListings,32);assert.equal(eco.auctionPool,16);assert.equal(sa.v34CatalogSnapshot().builds,8);assert.equal(sa.v33CatalogSnapshot().materials,60);assert.equal(sa.v33CatalogSnapshot().recipes,32);assert.equal(sa.v32CatalogSnapshot().equipment,68);assert.equal(sa.v31CatalogSnapshot().manuals.length,32);assert.equal(sa.v31CatalogSnapshot().spells.length,72);
// Save/reload keeps the new progression axis.
const saved=sa.getState(),rd=loadState(saved),ra=rd.window.__TAIXUAN_TEST__,rs=ra.getState();assert.equal(rs.saveSchemaVersion,33);assert.equal(rs.player.v36SpaceInsight,saved.player.v36SpaceInsight);assert.equal(rs.player.v36VoidVersion,1);
// Future schema34 must never be overwritten.
const future=ra.getState();future.saveSchemaVersion=34;future.version='future-v36';const futureRaw=JSON.stringify(future),fd=makeDom(futureRaw);fd.window.document.getElementById('continueBtn').click();assert.equal(fd.window.localStorage.getItem(SAVE_KEY),futureRaw);assert.equal(fd.window.__TAIXUAN_TEST__.getState(),null);
console.log('V36_REGRESSION_PASS',JSON.stringify({version:'3.6.0',schema:33,realms:30,regions:16,routes:26,materials:60,recipes:32,manuals:32,spells:72,equipment:68,artifacts:32,enemies:60,spaceInsight:true,voidEssence:true,refiningBreakthrough:true,voidBacklash:true,spaceCombat:true,v35Preserved:true,futureSaveProtected:true}));
